name: docs-build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docs
        uses: laminas/documentation-theme/github-actions/docs@master
        env:
          DOCS_TOKEN: ${{ secrets.ORGANIZATION_ADMIN_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
